import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.Base64;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

public class TestAbaQr {
    public static void main(String[] args) throws Exception {
        // Just mocking the logic to see if it compiles and the regex works
        String url = "https://checkout-sandbox.payway.com.kh/checkout/eyJxcl9zdHJpbmciOiIwMDAyMDEwMTAyMTIzMDUxMDAxNmFiYWFraHBweHh4QGFiYWEwMTE1MTExMTExMTExMTExMTExMDIwOEFCQSBCYW5rNTIwNDU5OTk1MzAzODQwNTQwNTE1LjAwNTgwMktINTkwOFx1MTc5Rlx1MTdCQlx1MTc4MSBcdTE3OUNcdTE3QjhcdTE3OUE6NjAwMDYyMjgwNTA3MDEyODQ0NTA3MTMxNzg3NjAwODczNTQ5OTk3NTAwMTMxNzg3NjAwODc4MzA1MDExMzE3OTAxOTI4NzgxODU2NzE3MDAxM0YxQkYwMTY0MTFGREE2ODA0UE9OTDY5MDhwdXJjaGFzZTYzMDRCQzU5IiwiZG93bmxvYWRfcXIiOiJodHRwczovL2NoZWNrb3V0LXNhbmRib3gucGF5d2F5LmNvbS5raC9hcGkvcGF5bWVudC1nYXRld2F5L3YzL3BheW1lbnRzL2Rvd25sb2FkLWNoZWNrb3V0LXFyP2FiYV9kYXRhPU4xQjRRbXBEUkZZeGNqUkxhMjFsVTBSUlJVNVlaM0ZEU2xoMFp6RXJhQzlYSzJSNE5VaEtTRlJWYkdOeFdra3paMmcxZGtoeGFqVmpZMHRXY0dGdk5UWk9NbXRTUjBvemQyWkNXVUZEZUdWeFZHMWtjbUpZVlZSbVIyZDVUWGxWV2k5MVdXNDRhR1l2TWpROSIsInN0ZXAiOiJhYmFwYXlfa2hxcl9yZXF1ZXN0X3FyIiwidHJhbnNhY3Rpb25fc3VtbWFyeSI6eyJvcmRlcl9kZXRhaWxzIjp7InN1YnRvdGFsIjoxNS4wMCwic2hpcHBpbmciOjAsInZhdF9lbmFibGVkIjoiMCIsInZhdCI6IjAiLCJ2YXRfYW1vdW50IjowLCJ0b3RhbCI6MTUuMDAsImN1cnJlbmN5IjoiVVNEIiwidHJhbnNhY3Rpb25fZmVlIjowLCJvcmRlcl9pZCI6IjE3ODc2MDA4NzM1NDkifSwibWVyY2hhbnQiOnsibmFtZSI6Ilx1MTc5Rlx1MTdCQlx1MTc4MSBcdTE3OUNcdTE3QjhcdTE3OUE6IiwibG9nbyI6IiIsInByaW1hcnlfY29sb3IiOiIjMDBiY2Q0IiwiY2FuY2VsX3VybCI6IiIsInRoZW1lcyI6ImRlZmF1bHQiLCJmb250X2ZhbWlseSI6IlNGX1Byb19EaXNwbGF5IiwiZm9udF9zaXplIjoxNCwiYmdfY29sb3IiOiIjZmZmZmZmIiwiYm9yZGVyX3JhZGl1cyI6Nn19LCJ0b2tlbiI6IlhsWXczaFx1MDAyQkNqbllhNnpZdzRYUDBOWEJVUndManhvUGYzcWh3ZmY0YllVQ01cdTAwMkJ4ZUN3UTg0eVJXSnlBV2lVOUdxOWZjZUFLUkNkcGNBdmI1Y1puNzR5Wnpwa0xHMDhGS3pzZU1kYTZ5MWl1UT0iLCJ0b2tlbl90aW1lIjoxNzg3NjAwODc4LCJhYmFfZGF0YSI6Ilx1MDAyQkZYYzRlaktKNEVHXHUwMDJCNHdXQ0JQVzF0Q3RydnFjYkhNQlM0MVBYV3hKeENOelg5SWJ4QUpiWTBUVHZDdWgzMEx5S1dMSEVIQmlKOUo0eGJhTWdaVjIzb0FNVER3WktCVHFIdzdtVHR1T0ZsNFBXWXBLXHUwMDJCTkVIT0F6V21zVWlkRVE2TmN6WlNJUEMzYjVxY0d5eS9NOWZhXHUwMDJCVnlyNThFclNsdVpMVGRRdEU1Z0tuRi9FODRFZW9KUE4wWm1TUElNSGExOEo0NWl5Zmkza1padXVnZlVEVHZXL1NZeVJFczNNcTkwdC9CNlhsRjd4cEYyeTZla0k3WmFjOHRucGFnZzd4Y3paQ3F6M1IxN3RoNXlsQXcxSVhrWUc0RGs0SHBDOWJtdG5YR3dlTS9nTE1cdTAwMkJnSUZjcnVLdHFRRWtQUzVIczFlSTdYZ1x1MDAyQnZzTEc4STJKUHk0ZDRVWlx1MDAyQjFoXHUwMDJCVTVSV0txVzh0cGpGUC9ST2hZa1J6Q1NldkE0NzF6QW1DenFJZGFESHNSNy8wc0dVOTltTDhxeFNrTVVqNms4NGNpWnFJb29kVkFla1BSQnovWkZlcm51NHhWc1hQT1x1MDAyQkwwRmtjT2VuTmt1TWo0WG9cdTAwMkJhM1BnOEtpTnRTSnlFZE9FcDFzdlRxZEdHZXpob1k4eVVtb1dzOFpzeWZUL3pQakg1R0ZJMXNcdTAwMkJyNy9cdTAwMkJzU2pkbFx1MDAyQnllSFNcdTAwMkIwNUVYMUo2RlhqdDVNYU1STi9lTlhvV2tweEFSNzA9IiwicGF5bWVudF9vcHRpb25zIjp7ImFiYXBheV9raHFyIjp7ImxhYmVsIjoiQUJBIEtIUVIifX0sImV4cGlyZV9pbiI6MTc4NzYwMTE3OCwiZXhwaXJlX2luX3NlYyI6IjMwMCIsInN0YXR1cyI6eyJ2ZXJzaW9uIjoidjMiLCJjb2RlIjoiMDAiLCJtZXNzYWdlIjoiU3VjY2VzcyEiLCJ0cmFuX2lkIjoiMTc4NzYwMDg3MzU0OSIsImxhbmciOiJlbiIsInRyYWNlX2lkIjoiMmZiYTQ3MmMyN2VhODA2MjI3MzBiZDhlM2Q1ZDI4ODAifX0=";
        String base64 = url.substring(url.lastIndexOf('/') + 1);
        String json = new String(Base64.getDecoder().decode(base64), StandardCharsets.UTF_8);
        Matcher m = Pattern.compile("\"qr_string\"\\s*:\\s*\"([^\"]+)\"").matcher(json);
        if (m.find()) {
            System.out.println("Found QR: " + m.group(1));
        } else {
            System.out.println("QR not found in JSON");
        }
    }
}
