package com.eventbooking.model.ABA;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

    @lombok.Data
    @JsonIgnoreProperties(ignoreUnknown = true)
    public class BankPaymentResponse {

        @JsonProperty("qrString")
        private String qrString;

        @JsonProperty("qrImage")
        private String qrImage;

        @JsonProperty("abapay_deeplink")
        private String abapayDeeplink;

        @JsonProperty("description")
        private String description;

        /** Values generated by this application for displaying the KHQR payment card. */
        private String displayName;
        private String displayAmount;
        private String displayCurrency;

        @JsonProperty("status")
        private Status status;

        @lombok.Data
        @JsonIgnoreProperties(ignoreUnknown = true)
        public static class Status {
            private String version;
            private String code;
            private String message;
            @JsonProperty("tran_id")
            private String tranId;
            private String lang;
            @JsonProperty("trace_id")
            private String traceId;
        }
    }


